# Generated by Django 5.0 on 2024-01-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Tv'), (2, 'Mobile'), (3, 'Washing Machine'), (4, 'Microwave'), (5, 'Air Conditioners')], verbose_name='Category'),
        ),
    ]
